[workspace]
resolver = "2"
members = [
    "subprojects/nx-alloc",
    "subprojects/nx-cpu",
    "subprojects/nx-rand",
    "subprojects/nx-std",
    "subprojects/nx-std-sync",
    "subprojects/nx-svc",
    "subprojects/nx-sys-mem",
    "subprojects/nx-sys-sync",
    "subprojects/nx-sys-thread",
    "subprojects/nx-time",
]
