[package]
name = "nx-sys-mem"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sys_mem"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_sys_mem FFI
ffi = []

[dependencies]
intrusive-collections = "0.9.7"
nx-alloc = { version = "0.1.0", path = "../nx-alloc", features = ["global-allocator"] }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-rand = { version = "0.1.0", path = "../nx-rand" }
nx-std-sync = { version = "0.1.0", path = "../nx-std-sync" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
thiserror = { version = "2.0.12", default-features = false }
