[package]
name = "nx-svc"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_svc"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[dependencies]
bitflags = "2.9"
panic-abort = "0.3.2"
panic-halt = "1.0.0"
thiserror = { version = "2.0", default-features = false }
