[package]
name = "nx-svc"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_svc"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_svc FFI
ffi = []

[dependencies]
bitflags = "2.9"
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
thiserror = { version = "2.0", default-features = false }
