[package]
name = "nx-sf"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sf"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_sf FFI
ffi = []

[dependencies]
modular-bitfield = "0.11"
static_assertions = "1.1"
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
nx-sys-thread-tls = { version = "0.1.0", path = "../nx-sys-thread-tls" }
