[package]
name = "nx-sys-sync"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sys_sync"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_sys_sync FFI
ffi = []

[dependencies]
nx-cpu = { version = "0.1.0", path = "../nx-cpu" }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
static_assertions = "1.1.0"
