[package]
name = "nx-sys-thread"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sys_thread"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_sys_thread FFI
ffi = []

[dependencies]
nx-cpu = { version = "0.1.0", path = "../nx-cpu" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
panic-abort = "0.3.2"
panic-halt = "1.0.0"
static_assertions = "1.1.0"
thiserror = { version = "2.0.12", default-features = false }
