[package]
name = "nx-cpu"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_cpu"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
