[package]
name = "nx-time"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_time"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_time FFI
ffi = []

[dependencies]
nx-cpu = { version = "0.1.0", path = "../nx-cpu" }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
static_assertions = "1.1.0"
thiserror = { version = "2.0.11", default-features = false }
